services:
  db-preprod:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: churches
    ports:
      - "5432:5432"

  db-vigo:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: church_vigo
    ports:
      - "5433:5432"

  db-madrid:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: church_madrid
    ports:
      - "5434:5432"

  db-barcelona:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: church_barcelona
    ports:
      - "5435:5432"